name: feed
description: A new Flutter package project.
version: 1.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
